/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Staff;

import org.junit.Test;

import com.staff.main.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
    }
}
